export const GET_COIN = "GET_COIN";
export const GET_DETAIL_COIN = "GET_DETAIL_COIN";
export const FAILED_GET_DETAIL_COIN = "FAILED_GET_DETAIL_COIN";
export const GET_HISTORY_COIN = "GET_HISTORY_COIN";

export const GET_INFORMATION_MARKET_CAP = "GET_INFORMATION_MARKET_CAP";
